# .github/workflows/delete_PR_images.yml
name: Remove obsolete PR images from registry

on:
  pull_request:
    types: [closed]

env:
  PACKAGE_NAME: librespot-shairport-snapserver

jobs:
  delete-pr-images:
    # Run only for PRs from the same repository, not from forks
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Get all version IDs for the PR
        id: versions
        run: |
          # Fetch all package versions and save to a file
          curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/users/${{ github.repository_owner }}/packages/container/${{ env.PACKAGE_NAME }}/versions" > containerMeta.json

          # Use jq to find all versions where at least one tag starts with the PR prefix, then get their IDs
          VERSION_IDS=$(jq -r '[.[] | select(.metadata.container.tags[]? | startswith("pr-${{ github.event.pull_request.number }}-")).id] | unique | .[]' containerMeta.json)
          
          if [ -z "$VERSION_IDS" ]; then
            echo "No container images found for PR #${{ github.event.pull_request.number }}. Nothing to delete."
          else
            echo "Found version IDs to delete: $VERSION_IDS"
          fi
          
          # Pass the list of IDs to the next step
          echo "VERSION_IDS<<EOF" >> "$GITHUB_ENV"
          echo "$VERSION_IDS" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

      - name: Delete PR images from registry
        # Only run if version IDs were found
        if: env.VERSION_IDS != ''
        uses: actions/delete-package-versions@v5
        with:
          package-version-ids: ${{ env.VERSION_IDS }}
          package-type: container
          package-name: ${{ env.PACKAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }} # Use default token for this action